POST http://localhost:3000/items
Content-Type: application/json

{"url":  "https://www.ebay.com/itm/265045798035?_trkparms=amclksrc%3DITM%26aid%3D1110006%26algo%3DHOMESPLICE.SIM%26ao%3D1%26asc%3D240680%26meid%3D8191c6c856f9482497bc3309b6d64111%26pid%3D101195%26rk%3D1%26rkt%3D12%26sd%3D154926682565%26itm%3D265045798035%26pmt%3D1%26noa%3D0%26pg%3D2047675%26algv%3DSimplAMLv9PairwiseWebMskuAspectsV202110NoVariantSeedKnnRecallV1%26brand%3Dadidas&_trksid=p2047675.c101195.m1851&amdata=cksum%3A2650457980358191c6c856f9482497bc3309b6d64111%7Cenc%3AAQAHAAABIK6kjqEQMYM5Aq%252BOhcaIlwco9wYktoCXAP3D6Fo7POUdlJK1eqFqv5Y7huO6nLq7hjqYjs5sEMudJpf20WlRkR6a5jE4PtGlm2LYoavzhccT%252BP%252Bh0aIHPAiHv26animaZ4LvULXObn12H7bwWPvUpqh5e5aXgjr59Y395NfmvcjSvo7v3W6sDTfUK8HSnOVfkEUolnWJUgcukBTnPo2HGjohUcuQzBzKxI8vEmNr8nhBPG8XT2q9LJZiqyZVZ%252B%252Bhagf8sGgXRbyirlIr057kFc1tqTA12wEU%252B2kXhTJ%252F6CSlRfIN%252BFkK%252BUjDbgmh2AbLl8pyaS1HB8kNgGLUwk3AzpkquwtegDE6AAOIar4MAyJVucFoFrdFGQqohl6j8ZgDaQ%253D%253D%7Campid%3APL_CLK%7Cclp%3A2047675"}

###
POST http://localhost:3000/items
Content-Type: application/json

{"url":  "https://www.amazon.com/Nike-Experience-White-Cool-Grey-Reflective-Regular/dp/B00V88DL72/"}

###
GET http://localhost:3000/items
Accept: application/json


###
GET http://localhost:3000/items?name=nike
Accept: application/json

###
